imediaelement.default.settings:
  type: config_object
  label: 'Default Media Dimensions'
  mapping:
    default_video_width:
      type: integer
      label: 'Default Video Width'
    default_video_height:
      type: integer
      label: 'Default Video Height'
    default_audio_width:
      type: integer
      label: 'Default Audio Width'
    default_audio_height:
      type: integer
      label: 'Default Audio Height'

imediaelement.settings:
  type: config_object
  label: 'imediaelement Settings'
  mapping:
    class_prefix:
      type: string
      label: 'Class Prefix'
    video_width:
      type: integer
      label: 'Video Width'
    video_height:
      type: integer
      label: 'Video Height'
    audio_width:
      type: integer
      label: 'Audio Width'
    audio_height:
      type: integer
      label: 'Audio Height'

imediaelement.formatter.media:
  type: mapping
  label: 'imediaelement.js format settings'
  mapping:
    download_link:
      type: boolean
      label: 'Download Link'
    download_text:
      type: string
      label: 'Download Text'

field.formatter.settings.imediaelement_file_video:
  type: imediaelement.formatter.media
  label: 'imediaelement.js Video formatter settings'
  mapping:
    poster_image_field:
      type: string
      label: 'Poster Image Field'
    poster_image_style:
      type: string
      label: 'Poster Image Style'

field.formatter.settings.imediaelement_file_audio:
  type: imediaelement.formatter.media
  label: 'imediaelement.js Audio formatter settings'
